name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install React and Node.js dependencies
        run: |
          npm install react
          npm install react-dom


      - name: Format Code with Prettier
        run: |
          cd NOTES
          cd src
          npx prettier . --write

      - name: Check Code Formatting
        run: |
          cd NOTES
          cd src
          npx prettier . --check

      - name: Run JSCPD
        run: |
          cd src
          npx jscpd 

