name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install React and Node.js dependencies
        run: |
          npm install react
          npm install react-dom

      ## Prettier, uma ferramenta popular para garantir a consistência e a legibilidade do código.
      ## https://prettier.io/
      - name: Format Code with Prettier
        run: |
          cd NOTES
          cd src
          npx prettier . --write

      - name: Check Code Formatting
        run: |
          cd NOTES
          cd src
          npx prettier . --check

      ## JSCPD, uma ferramenta de detecção de código duplicado em projetos JavaScript
      ## https://www.npmjs.com/package/jscpd 
      - name: Run JSCPD
        run: |
          cd NOTES
          cd src
          npx jscpd 

      ## ESLint analisa estaticamente seu código para encontrar problemas rapidamente. 
      ## https://eslint.org/ 
      - name: Run ESLint
        run: |
          cd NOTES
          cd src
          npm lint --ext js,jsx --report-unused-disable-directives

